### ISSUE TITLE
Portfolio Tracker

### ISSUE THREAD

**Issue by nirajgiriXD** [ChandraByte/hamro-nepse#40]
## Description

A feature for giving users information about the total profit / loss on a day and overall profit / loss.

---

## Expectation

As a user, I should have the capability and feature of

- [x] Adding stocks to my portfolio list
- [x] Seeing the turnover of the day i.e. total profit / loss
- [x] Seeing net turnover for shares bought and sold
- [x] Price calculation for net turnover should have tax or other expense charges included

---

## Reference

- https://meroshare.cdsc.com.np/#/portfolio
